[build]
target = "x86_64-unknown-linux-gnu"


[target.x86_64-unknown-linux-gnu]
runner = "bash -c "

[env]
LD_PRELOAD = "target/debug/liblibrary.so"
AUTO_COLOR_TARGET = "deps\\/tests-[a-f0-9]{16}$"
AUTO_COLOR_LOG = "warn"
RUST_TEST_THREADS = "1"